version: '3'
services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1
      - TZ=UTC
    ports:
      - 1433:1433
    privileged: true
